version: '3'

services:
    irods-catalog:
        build:
            context: irods_catalog
        # 5432 is exposed by default and can conflict with other postgres containers.
        # When the metalnx-db service is no longer needed, this stanza can be removed.
        ports:
            - "5430:5432"
        environment:
            - POSTGRES_PASSWORD=testpassword

    irods-catalog-provider:
        build:
            context: irods_catalog_provider
        healthcheck:
            test: ["CMD", "su", "-", "irods", "-c", "ils || exit 1"]
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 20s
            start_interval: 2s
        depends_on:
            - irods-catalog

    irods-client-icommands:
        build:
            context: irods_client_icommands
        depends_on:
            - irods-catalog-provider

    irods-client-http-api:
        image: irods/irods_http_api:latest
        volumes:
            - ./irods_client_http_api/config.json:/config.json:ro
        ports:
            - "9001:9000"
        restart: on-failure
        depends_on:
            irods-catalog-provider:
                condition: service_healthy

    irods-client-rest-cpp:
        build:
            context: irods_client_rest_cpp
            dockerfile: irods_client_rest_cpp.Dockerfile
        volumes:
            - ./irods_client_rest_cpp/irods_client_rest_cpp.json:/etc/irods_client_rest_cpp/irods_client_rest_cpp.json:ro
        depends_on:
            - irods-catalog-provider

    nginx-reverse-proxy:
        build:
            context: irods_client_rest_cpp
            dockerfile: nginx.Dockerfile
        ports:
            - "80:80"
        depends_on:
            - irods-client-rest-cpp

    irods-client-zmt:
        build:
            context: irods_client_zone_management_tool
        environment:
            - REACT_APP_REST_API_URL=http://localhost/irods-rest/0.9.3
            - REACT_APP_APPBAR_LOGO=iRODS-logo.jpg
            - REACT_APP_LOGIN_LOGO=iRODS-logo-1.png
            - REACT_APP_BRANDING_NAME=Zone Management Tool
            - REACT_APP_PRIMARY_COLOR=#04bdaf
        volumes:
            - ./irods_client_zone_management_tool:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "9000:3000"
        depends_on:
            - nginx-reverse-proxy

    metalnx-db:
        build:
            context: metalnx-db
        environment:
            - POSTGRES_PASSWORD=password

    metalnx:
        build:
            context: metalnx
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - "./metalnx/mylocal-irods-ext:/etc/irods-ext"
        depends_on:
            - metalnx-db
            - irods-catalog-provider

    irods-client-nfsrods:
        build:
            context: irods_client_nfsrods
        ports:
            - "2050:2049"
        volumes:
            - "./irods_client_nfsrods/nfsrods_config:/nfsrods_config:ro"
            - "/etc/passwd:/etc/passwd:ro"
        depends_on:
            - irods-catalog-provider

    minio:
        image: minio/minio:RELEASE.2022-10-29T06-21-33Z
        command: server --address ":19000" --console-address ":19001" /data
        ports:
            - "19000:19000"
            - "19001:19001"
        volumes:
          - ./minio-data:/data
        environment: 
          MINIO_ROOT_USER: irods
          MINIO_ROOT_PASSWORD: irodsadmin

