name: irods-demo

services:
    irods-catalog:
        build:
            context: irods_catalog
        # 5432 is exposed by default and can conflict with other postgres containers.
        # When the metalnx-db service is no longer needed, this stanza can be removed.
        ports:
            - "5430:5432"
        environment:
            - POSTGRES_PASSWORD=testpassword
        restart: always

    irods-catalog-provider:
        build:
            context: irods_catalog_provider
        shm_size: 500mb
        healthcheck:
            test: ["CMD", "su", "-", "irods", "-c", "./irodsctl status | grep Process"]
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 20s
            start_interval: 10s
        restart: always
        depends_on:
            - irods-catalog
            - minio

    irods-catalog-consumer:
        build:
            context: irods_catalog_consumer
        shm_size: 500mb
        healthcheck:
            test: ["CMD", "su", "-", "irods", "-c", "./irodsctl status | grep Process"]
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 20s
            start_interval: 10s
        restart: always
        depends_on:
            irods-catalog-provider:
                condition: service_healthy

    irods-client-icommands:
        build:
            context: irods_client_icommands
        depends_on:
            irods-catalog-provider:
                condition: service_healthy

    irods-client-s3-api:
        image: irods/irods_s3_api:0.3.0
        volumes:
            - ./irods_client_s3_api/config.json:/config.json:ro
        ports:
            - "9002:9000"
        restart: on-failure
        depends_on:
            irods-catalog-provider:
                condition: service_healthy

    irods-client-http-api:
        image: irods/irods_http_api:0.5.0
        volumes:
            - ./irods_client_http_api/config.json:/config.json:ro
        ports:
            - "9001:9000"
        restart: on-failure
        depends_on:
            irods-catalog-provider:
                condition: service_healthy

    nginx-reverse-proxy:
        build:
            context: nginx
        ports:
            - "80:80"
        depends_on:
            irods-catalog-provider:
                condition: service_healthy

    irods-client-zmt:
        build:
            context: irods_client_zone_management_tool
        environment:
            - REACT_APP_HTTP_API_URL=http://localhost/irods-http-api/0.4.0
            - REACT_APP_APPBAR_LOGO=iRODS-logo.jpg
            - REACT_APP_LOGIN_LOGO=iRODS-logo-1.png
            - REACT_APP_BRANDING_NAME=Zone Management Tool
            - REACT_APP_PRIMARY_COLOR=#04bdaf
        volumes:
            - ./irods_client_zone_management_tool:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "9000:3000"
        depends_on:
            nginx-reverse-proxy:
                condition: service_started
            irods-client-http-api:
                condition: service_started

    metalnx-db:
        build:
            context: metalnx-db
        environment:
            - POSTGRES_PASSWORD=password

    metalnx:
        build:
            context: metalnx
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - "./metalnx/mylocal-irods-ext:/etc/irods-ext"
        depends_on:
            metalnx-db:
                condition: service_started
            irods-catalog-provider:
                condition: service_healthy

    irods-client-nfsrods:
        build:
            context: irods_client_nfsrods
        ports:
            - "2050:2049"
        volumes:
            - "./irods_client_nfsrods/nfsrods_config:/nfsrods_config:ro"
            - "/etc/passwd:/etc/passwd:ro"
        depends_on:
            irods-catalog-provider:
                condition: service_healthy

    minio:
        image: minio/minio:RELEASE.2024-09-13T20-26-02Z
        ports:
            - "19000:19000"
            - "19001:19001"
        volumes:
          - ./minio-data:/data
        command: minio server /data
        environment: 
          MINIO_ROOT_USER: irods
          MINIO_ROOT_PASSWORD: irodsadmin
          MINIO_ADDRESS: ":19000"
          MINIO_CONSOLE_ADDRESS: ":19001"
